#!/bin/sh
#
# PROVIDE: caddy
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="caddy"
rcvar=caddy_enable

load_rc_config $name

: ${caddy_enable:=NO}
: ${caddy_config_file:="/usr/local/etc/caddy/Caddyfile"}

pidfile="/var/run/caddy.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r /usr/local/bin/caddy run --config ${caddy_config_file} > /dev/null 2>&1"

# Path to setup script
caddy_setup_script="/usr/local/opnsense/scripts/Pischem/Caddy/setup.sh"

start_precmd=caddy_start_precmd
restart_precmd=caddy_start_precmd

caddy_start_precmd()
{
    # Call the setup script before starting the service
    sh ${caddy_setup_script}
}

run_rc_command "$1"

