PLUGIN_NAME=     caddy
PLUGIN_VERSION=  1.1.2b
PLUGIN_COMMENT=  Caddy Web Server configuration plugin
PLUGIN_DEPENDS=  caddy
PLUGIN_MAINTAINER= cedrik@pischem.com
PLUGIN_WWW= https://github.com/Monviech/os-caddy-plugin

.include "../../Mk/plugins.mk"
