PLUGIN_NAME=            caddy
PLUGIN_VERSION=         1.3.3
PLUGIN_DEPENDS=         caddy
PLUGIN_COMMENT=         Easy to configure Reverse Proxy with Automatic HTTPS
PLUGIN_MAINTAINER=      cedrik@pischem.com
PLUGIN_WWW=             https://github.com/Monviech/os-caddy-plugin

.include "../../Mk/plugins.mk"
